config/routes.rb
Rails.application.routes.draw do
  
  
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  # resources :message, only: [:new, :create]
  post 'message', to: 'messages#create'
  mount ActionCable.server, at: '/cable'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :messages
  validates :username, length: { minimum: 3, maximum: 25 },
            uniqueness: { case_sensitive: false }, presence: true
  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to do that"
      redirect_to login_path
    end
  end
  
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
  
  def index
    @message = Message.new
    @messages = Message.all
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  
  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast('chatroom_channel', {content: new_chat_message(message)})
    end
  end
  
  private
  
  def message_params
    params.require(:message).permit(:body)
  end
  
  def new_chat_message(message)
    render(partial: 'message', locals: {message: message})
  end
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect,  only: [:new, :create]

  def new
  end
  
  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Login Successful!"
      redirect_to root_path
    else
      flash.now[:error] = "Login unsuccessful. Check username or password"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "Logout Successfull"
    redirect_to login_path
  end
  
  private
  
  def logged_in_redirect
    if logged_in?
      flash[:error] = "You're already logged in, dumbass."
      redirect_to root_path
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "Welcome, #{@user.username}, you have successfully signed up!"
      redirect_to login_path
    else
      flash[:error] = @user.errors.full_messages[0]
      render 'new'
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular orange comments icon"></i>
  Say Something
</h2>

<div class="ui two column grid">
  
  <div class="ui twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="chatwindow">
        <div class="ui feed" id="chatstream">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_with(scope: @message, url: message_path, local: false,
            html: { class: "ui reply form", role: "form"} ) do |form| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= form.text_field :body, placeholder: "Enter a message" %>
              <%= form.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %> 
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  
  <div class="ui four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical pointing menu">
          <%= link_to "Chatroom", root_path, class: "item" %>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
  
</div>

app/views/layouts/_any_messages.html.erb
<% flash.each do |message_type, message_text| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_text %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Chatroom", root_path, class: "item" %>
<a class="item">
  Messages
</a>
<div class="right menu">
  <div class="ui dropdown item">
    Account <i class="dropdown icon"></i>
    <div class="menu">
      <% if logged_in? %>
        <%= link_to "Log Out", logout_path, method: :delete, class: "item" %>
      <% else %>
        <%= link_to "Log In", login_url, class: "item" %>
      <% end %>
    </div>
  </div>
  <% unless logged_in? %>
    <div class="item">
        <%= link_to "Sign Up", signup_path, class: "ui orange button" %>
    </div>
  <% end  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" />
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui small inverted menu">
      <div class="ui container">
        <%= render 'layouts/navigation' %>
      </div>
    </div>    
    <div class="ui container">
      <%= render 'layouts/any_messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
  <div class="event">
    <div class="content">
      <div class="summary">
         <em><%= message.user.username %></em>:  <%= message.body %>
      </div>
    </div>
  </div>

app/views/users/_form.html.erb
<div class="ui container center aligned">
  <div class="ui placeholder segment">

        <%= form_with(model: @user, class:"ui large equal width form", local: true) do |f| %>
          <div class="fields">
            <div class="field">
              <%= f.label :username %>
              <%= f.text_field :username, placeholder:"Choose a Username" %>
            </div>
            <div class="field">
              <%= f.label :password %>
              <%= f.password_field :password, placeholder:"Enter a password" %>
            </div>
          </div>
          <button class="ui orange submit button" type="submit">Submit</button>
        <% end %>
   </div>       
</div>

app/views/users/new.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular orange user icon"></i>
  Sign Up
</h2>
<%= render 'form' %>